package consejodepartamental.ui;

import consejodepartamental.entity.Organizador;
import consejodepartamental.logic.Controlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class BuscarOrganizadorFrame extends javax.swing.JFrame {

    private Controlador controlador;
    private List<Organizador> organizadores;
    private SaveModularEventFrame parentFrame;

    public BuscarOrganizadorFrame(SaveModularEventFrame parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        this.controlador = new Controlador();
        organizadores = controlador.obtenerOrganizadoresConFiltros(null, null);
        llenarTabla();
    }

    @Override
    public void dispose() {
        this.controlador.finalizar();
        super.dispose();
    }

    public void llenarTabla() {

        DefaultTableModel tableModel = (DefaultTableModel) this.organizadoresTable.getModel();
        tableModel.setRowCount(0); //Limpiar tabla
        Object cells[] = new Object[6];

        for (Organizador org : organizadores) {
            cells[0] = false;
            cells[1] = org.getCip();
            cells[2] = org.getDni();
            cells[3] = org.getOrganizador();
            cells[4] = org.getCelular();
            cells[5] = org.getCorreo();

            tableModel.addRow(cells);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        cipLabel = new javax.swing.JLabel();
        cipTexField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreTexField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizadoresTable = new javax.swing.JTable();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(23, 33, 42));

        cipLabel.setBackground(new java.awt.Color(255, 255, 255));
        cipLabel.setFont(new java.awt.Font("Corbel Light", 0, 16)); // NOI18N
        cipLabel.setForeground(new java.awt.Color(255, 255, 255));
        cipLabel.setText("CIP");

        nombreLabel.setBackground(new java.awt.Color(255, 255, 255));
        nombreLabel.setFont(new java.awt.Font("Corbel Light", 0, 16)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Nombres");

        organizadoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "CIP", "DNI", "Organizador", "Celular", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizadoresTable);
        if (organizadoresTable.getColumnModel().getColumnCount() > 0) {
            organizadoresTable.getColumnModel().getColumn(0).setPreferredWidth(4);
            organizadoresTable.getColumnModel().getColumn(1).setPreferredWidth(5);
            organizadoresTable.getColumnModel().getColumn(2).setPreferredWidth(5);
            organizadoresTable.getColumnModel().getColumn(3).setPreferredWidth(30);
            organizadoresTable.getColumnModel().getColumn(4).setPreferredWidth(10);
            organizadoresTable.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(23, 33, 42));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/search.png"))); // NOI18N
        searchButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okBtn)
                        .addGap(19, 19, 19)
                        .addComponent(cancelBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cipTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreTexField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(309, 309, 309)
                                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addGap(0, 0, 0)
                        .addComponent(nombreTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(cipLabel)
                        .addGap(0, 0, 0)
                        .addComponent(cipTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        List<Organizador> organizadoresSeleccionados = new ArrayList<>();

        DefaultTableModel tableModel = (DefaultTableModel) this.organizadoresTable.getModel();

        for (int i = 0; i < tableModel.getRowCount(); i++) {

            Boolean isSelected = (Boolean) tableModel.getValueAt(i, 0);
            if (isSelected) {
                Organizador org = new Organizador();
                org.setCip((int) tableModel.getValueAt(i, 1));
                org.setDni((String) tableModel.getValueAt(i, 2));
                org.setOrganizador((String) tableModel.getValueAt(i, 3));
                org.setCelular((String) tableModel.getValueAt(i, 4));
                org.setCorreo((String) tableModel.getValueAt(i, 5));

                organizadoresSeleccionados.add(org);
            }
        }

        this.parentFrame.llenarTablaOrganizadores(organizadoresSeleccionados);

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        String cip = this.cipTexField.getText();
        String nombre = this.nombreTexField.getText();
        organizadores = controlador.obtenerOrganizadoresConFiltros(cip, nombre);
        llenarTabla();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel cipLabel;
    private javax.swing.JTextField cipTexField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTexField;
    private javax.swing.JButton okBtn;
    private javax.swing.JTable organizadoresTable;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
