package consejodepartamental.ui;

import consejodepartamental.entity.Usuario;

/**
 *
 * @author Diego
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    private Usuario currentUser;
    private ListModularEventFrame modularEventFrame;

    public HomeFrame(Usuario currentUser) {
        initComponents();
        this.currentUser = currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        backgroundPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        managementMenu = new javax.swing.JMenu();
        transactionMenu = new javax.swing.JMenu();
        eventModularMenuItem = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        eventMenuItem = new javax.swing.JMenuItem();
        urlMenuItem = new javax.swing.JMenuItem();
        studentMenuItem = new javax.swing.JMenuItem();
        payAppMenuItem = new javax.swing.JMenuItem();
        payVoucherMenuItem = new javax.swing.JMenuItem();
        cipMenu = new javax.swing.JMenu();
        controlEquipmentMenu = new javax.swing.JMenu();
        emailMenuItem = new javax.swing.JMenuItem();
        ReportMenu = new javax.swing.JMenu();
        electionMenu = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(23, 33, 42));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        fileMenu.setText("Archivo");
        menuBar.add(fileMenu);

        managementMenu.setText("Mantenimiento");
        menuBar.add(managementMenu);

        transactionMenu.setText("Transacción");

        eventModularMenuItem.setText("Evento");

        jMenuItem1.setText("Eventos Modulares");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        eventModularMenuItem.add(jMenuItem1);

        eventMenuItem.setText("Evento");
        eventModularMenuItem.add(eventMenuItem);

        urlMenuItem.setText("URL Sesión y Grabación");
        eventModularMenuItem.add(urlMenuItem);

        transactionMenu.add(eventModularMenuItem);

        studentMenuItem.setText("Alumno");
        transactionMenu.add(studentMenuItem);

        payAppMenuItem.setText("Pagos App");
        transactionMenu.add(payAppMenuItem);

        payVoucherMenuItem.setText("Pagos Voucher");
        payVoucherMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payVoucherMenuItemActionPerformed(evt);
            }
        });
        transactionMenu.add(payVoucherMenuItem);

        cipMenu.setText("CIP Lambayeque");
        transactionMenu.add(cipMenu);

        controlEquipmentMenu.setText("Control de Equipos");
        transactionMenu.add(controlEquipmentMenu);

        emailMenuItem.setText("E-Mail Enviados");
        transactionMenu.add(emailMenuItem);

        menuBar.add(transactionMenu);

        ReportMenu.setText("Reportes");
        menuBar.add(ReportMenu);

        electionMenu.setText("Elecciones");
        menuBar.add(electionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payVoucherMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payVoucherMenuItemActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_payVoucherMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (this.modularEventFrame == null || !this.modularEventFrame.isDisplayable()) {
            this.modularEventFrame = new ListModularEventFrame();
            this.modularEventFrame.setVisible(true);
            this.modularEventFrame.setLocationRelativeTo(null);
        }else{
            this.modularEventFrame.requestFocus();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ReportMenu;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JMenu cipMenu;
    private javax.swing.JMenu controlEquipmentMenu;
    private javax.swing.JMenu electionMenu;
    private javax.swing.JMenuItem emailMenuItem;
    private javax.swing.JMenuItem eventMenuItem;
    private javax.swing.JMenu eventModularMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu managementMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem payAppMenuItem;
    private javax.swing.JMenuItem payVoucherMenuItem;
    private javax.swing.JMenuItem studentMenuItem;
    private javax.swing.JMenu transactionMenu;
    private javax.swing.JMenuItem urlMenuItem;
    // End of variables declaration//GEN-END:variables
}
