package consejodepartamental.ui;

import consejodepartamental.entity.Sesion;
import consejodepartamental.entity.Usuario;
import consejodepartamental.logic.Controlador;
import consejodepartamental.utils.Reloj;
import java.util.Random;

/**
 *
 * @author Diego
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    private Usuario currentUser;
    private Sesion currentSesion;
    private Controlador controlador;
    private ListModularEventFrame modularEventFrame;

    public HomeFrame(Usuario currentUser, Sesion currentSesion) {
        initComponents();
        this.currentUser = currentUser;
        this.currentSesion = currentSesion;
        this.controlador = new Controlador();
        actualizarValoresUsuario();
        actualizarTipoDeCambio();
        Reloj reloj = new Reloj((fecha, hora) -> {
            this.fechaLabel.setText(fecha);
            this.horaLabel.setText(hora);
        });
    }

    private void actualizarValoresUsuario() {
        if (this.currentUser != null) {
            this.dniLabel.setText(this.currentUser.getDni());
            this.nombreLabel.setText(this.currentUser.getApellidos().toUpperCase() + " " + this.currentUser.getNombres().toUpperCase());
            this.cargoLabel.setText(this.currentUser.getCargo().toUpperCase());
        } else {
            this.dniLabel.setText("");
            this.nombreLabel.setText("");
            this.cargoLabel.setText("");
        }
    }

    //Simula el tipo de cambio del dia
    private void actualizarTipoDeCambio() {
        Random random = new Random();
        //Compra: S/. 3.774
        //Venta: S/. 3.774
        double compraTipoDeCambio = random.nextDouble(3.5, 3.8);
        double ventaTipoDeCambio = compraTipoDeCambio + 0.025;

        this.dolarCompraLabel.setText(String.format("Compra: S/. %.3f", compraTipoDeCambio));
        this.dolarVentaLabel.setText(String.format("Venta: S/. %.3f", ventaTipoDeCambio));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        backgroundPanel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        simboloLabel = new javax.swing.JLabel();
        dolarVentaLabel = new javax.swing.JLabel();
        dolarCompraLabel = new javax.swing.JLabel();
        ventaDolarIcon = new javax.swing.JLabel();
        compraDolarIcon = new javax.swing.JLabel();
        servidorCorreoLabel = new javax.swing.JLabel();
        servidorHabilidadLabel = new javax.swing.JLabel();
        serverIcon1 = new javax.swing.JLabel();
        serverIcon2 = new javax.swing.JLabel();
        bottonPanel = new javax.swing.JPanel();
        bottonBarIcon = new javax.swing.JLabel();
        cargoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        horaLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        subtituloLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        managementMenu = new javax.swing.JMenu();
        transactionMenu = new javax.swing.JMenu();
        eventModularMenuItem = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        eventMenuItem = new javax.swing.JMenuItem();
        urlMenuItem = new javax.swing.JMenuItem();
        studentMenuItem = new javax.swing.JMenuItem();
        payAppMenuItem = new javax.swing.JMenuItem();
        payVoucherMenuItem = new javax.swing.JMenuItem();
        cipMenu = new javax.swing.JMenu();
        controlEquipmentMenu = new javax.swing.JMenu();
        emailMenuItem = new javax.swing.JMenuItem();
        ReportMenu = new javax.swing.JMenu();
        electionMenu = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(23, 33, 42));

        sideBarPanel.setBackground(new java.awt.Color(23, 33, 42));

        simboloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/colegio_ingenieros_logo.png"))); // NOI18N

        dolarVentaLabel.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        dolarVentaLabel.setForeground(new java.awt.Color(255, 255, 255));
        dolarVentaLabel.setText("Venta: S/. 3.774");

        dolarCompraLabel.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        dolarCompraLabel.setForeground(new java.awt.Color(255, 255, 255));
        dolarCompraLabel.setText("Compra: S/. 3.774");

        ventaDolarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/dolar.png"))); // NOI18N

        compraDolarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/dolar.png"))); // NOI18N

        servidorCorreoLabel.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        servidorCorreoLabel.setForeground(new java.awt.Color(255, 255, 255));
        servidorCorreoLabel.setText("Servidor de Correo");

        servidorHabilidadLabel.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        servidorHabilidadLabel.setForeground(new java.awt.Color(255, 255, 255));
        servidorHabilidadLabel.setText("Servidor de Habilidades");

        serverIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/encendido.png"))); // NOI18N

        serverIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/encendido.png"))); // NOI18N

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(sideBarPanelLayout.createSequentialGroup()
                            .addComponent(serverIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(servidorCorreoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sideBarPanelLayout.createSequentialGroup()
                            .addComponent(ventaDolarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dolarVentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sideBarPanelLayout.createSequentialGroup()
                            .addComponent(compraDolarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(dolarCompraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(simboloLabel))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(serverIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servidorHabilidadLabel)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(simboloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(dolarCompraLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dolarVentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sideBarPanelLayout.createSequentialGroup()
                        .addComponent(compraDolarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ventaDolarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(servidorCorreoLabel)
                    .addComponent(serverIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(servidorHabilidadLabel)
                    .addComponent(serverIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        bottonPanel.setBackground(new java.awt.Color(24, 33, 36));

        bottonBarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cd_lambayeque.png"))); // NOI18N

        cargoLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        cargoLabel.setForeground(new java.awt.Color(255, 255, 255));
        cargoLabel.setText("SISTEMAS");

        nombreLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("DELGADO CHAVARRI ANTHONY HARRIS");

        horaLabel.setFont(new java.awt.Font("Arial Narrow", 0, 48)); // NOI18N
        horaLabel.setForeground(new java.awt.Color(255, 255, 255));
        horaLabel.setText("11:40:10 a. m.");

        dniLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        dniLabel.setForeground(new java.awt.Color(255, 255, 255));
        dniLabel.setText("71919831");

        fechaLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setText("viernes, 14 de abril de 2023");

        javax.swing.GroupLayout bottonPanelLayout = new javax.swing.GroupLayout(bottonPanel);
        bottonPanel.setLayout(bottonPanelLayout);
        bottonPanelLayout.setHorizontalGroup(
            bottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottonPanelLayout.createSequentialGroup()
                .addComponent(bottonBarIcon)
                .addGap(18, 18, 18)
                .addGroup(bottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 483, Short.MAX_VALUE)
                .addGroup(bottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bottonPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fechaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(horaLabel))
                .addGap(23, 23, 23))
        );
        bottonPanelLayout.setVerticalGroup(
            bottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottonPanelLayout.createSequentialGroup()
                        .addComponent(dniLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreLabel)))
                .addGroup(bottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaLabel)
                    .addGroup(bottonPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cargoLabel)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bottonBarIcon))
        );

        tituloLabel.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("COLEGIO DE INGENIEROS DEL PERÚ");

        subtituloLabel.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        subtituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        subtituloLabel.setText("Consejo Departamental de Lambayeque");

        logoutBtn.setText("Cerrar Sesión");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(tituloLabel))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(384, 384, 384)
                                .addComponent(subtituloLabel)))
                        .addContainerGap(339, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn))))
            .addComponent(bottonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(logoutBtn)
                        .addGap(9, 9, 9)
                        .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtituloLabel))
                    .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bottonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fileMenu.setText("Archivo");
        menuBar.add(fileMenu);

        managementMenu.setText("Mantenimiento");
        menuBar.add(managementMenu);

        transactionMenu.setText("Transacción");

        eventModularMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/birrete.png"))); // NOI18N
        eventModularMenuItem.setText("Evento");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/libros.png"))); // NOI18N
        jMenuItem1.setText("Eventos Modulares");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        eventModularMenuItem.add(jMenuItem1);

        eventMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/libro.png"))); // NOI18N
        eventMenuItem.setText("Evento");
        eventModularMenuItem.add(eventMenuItem);

        urlMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/microfono.png"))); // NOI18N
        urlMenuItem.setText("URL Sesión y Grabación");
        eventModularMenuItem.add(urlMenuItem);

        transactionMenu.add(eventModularMenuItem);

        studentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/alumno.png"))); // NOI18N
        studentMenuItem.setText("Alumno");
        transactionMenu.add(studentMenuItem);

        payAppMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/celular.png"))); // NOI18N
        payAppMenuItem.setText("Pagos App");
        transactionMenu.add(payAppMenuItem);

        payVoucherMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/document.png"))); // NOI18N
        payVoucherMenuItem.setText("Pagos Voucher");
        payVoucherMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payVoucherMenuItemActionPerformed(evt);
            }
        });
        transactionMenu.add(payVoucherMenuItem);

        cipMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/cip.png"))); // NOI18N
        cipMenu.setText("CIP Lambayeque");
        transactionMenu.add(cipMenu);

        controlEquipmentMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/pc.png"))); // NOI18N
        controlEquipmentMenu.setText("Control de Equipos");
        transactionMenu.add(controlEquipmentMenu);

        emailMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/email.png"))); // NOI18N
        emailMenuItem.setText("E-Mail Enviados");
        transactionMenu.add(emailMenuItem);

        menuBar.add(transactionMenu);

        ReportMenu.setText("Reportes");
        menuBar.add(ReportMenu);

        electionMenu.setText("Elecciones");
        menuBar.add(electionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payVoucherMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payVoucherMenuItemActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_payVoucherMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (this.modularEventFrame == null || !this.modularEventFrame.isDisplayable()) {
            this.modularEventFrame = new ListModularEventFrame();
            this.modularEventFrame.setVisible(true);
            this.modularEventFrame.setLocationRelativeTo(null);
        } else {
            this.modularEventFrame.requestFocus();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        loginForm.setLocationRelativeTo(null);
        
        this.setVisible(false);
        this.dispose();
        this.controlador.eliminarSesion(this.currentSesion);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ReportMenu;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel bottonBarIcon;
    private javax.swing.JPanel bottonPanel;
    private javax.swing.JLabel cargoLabel;
    private javax.swing.JMenu cipMenu;
    private javax.swing.JLabel compraDolarIcon;
    private javax.swing.JMenu controlEquipmentMenu;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JLabel dolarCompraLabel;
    private javax.swing.JLabel dolarVentaLabel;
    private javax.swing.JMenu electionMenu;
    private javax.swing.JMenuItem emailMenuItem;
    private javax.swing.JMenuItem eventMenuItem;
    private javax.swing.JMenu eventModularMenuItem;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JMenu managementMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JMenuItem payAppMenuItem;
    private javax.swing.JMenuItem payVoucherMenuItem;
    private javax.swing.JLabel serverIcon1;
    private javax.swing.JLabel serverIcon2;
    private javax.swing.JLabel servidorCorreoLabel;
    private javax.swing.JLabel servidorHabilidadLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel simboloLabel;
    private javax.swing.JMenuItem studentMenuItem;
    private javax.swing.JLabel subtituloLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JMenu transactionMenu;
    private javax.swing.JMenuItem urlMenuItem;
    private javax.swing.JLabel ventaDolarIcon;
    // End of variables declaration//GEN-END:variables
}
