package consejodepartamental.ui;

/**
 *
 * @author Diego
 */
public class SaveModularEventFrame extends javax.swing.JFrame {

    /**
     * Creates new form SaveModularEventFrame
     */
    public SaveModularEventFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        mainDataPanel = new javax.swing.JPanel();
        organizerLabel = new javax.swing.JLabel();
        modalityLabel = new javax.swing.JLabel();
        enviromentLabel = new javax.swing.JLabel();
        trainingTypeLabel1 = new javax.swing.JLabel();
        topicLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        dateStartLabel = new javax.swing.JLabel();
        dateEndLabel = new javax.swing.JLabel();
        maxQuantityLabel = new javax.swing.JLabel();
        dayMaxLabel = new javax.swing.JLabel();
        totalHoursLabel = new javax.swing.JLabel();
        syllabusLabel = new javax.swing.JLabel();
        trainingTypeCombo = new javax.swing.JComboBox<>();
        organizerCombo = new javax.swing.JComboBox<>();
        modalityCombo = new javax.swing.JComboBox<>();
        enviromentCombo = new javax.swing.JComboBox<>();
        topicTextField = new javax.swing.JTextField();
        schedulePanel = new javax.swing.JPanel();
        categoryPanel = new javax.swing.JPanel();
        organizerPanel = new javax.swing.JPanel();
        settingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(23, 33, 42));

        tabPanel.setBackground(new java.awt.Color(23, 33, 42));
        tabPanel.setForeground(new java.awt.Color(255, 255, 255));
        tabPanel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N

        mainDataPanel.setBackground(new java.awt.Color(23, 33, 42));
        mainDataPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainDataPanel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N

        organizerLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        organizerLabel.setForeground(new java.awt.Color(255, 255, 255));
        organizerLabel.setText("Organizadores");

        modalityLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        modalityLabel.setForeground(new java.awt.Color(255, 255, 255));
        modalityLabel.setText("Modalidad");

        enviromentLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        enviromentLabel.setForeground(new java.awt.Color(255, 255, 255));
        enviromentLabel.setText("Ambiente");

        trainingTypeLabel1.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        trainingTypeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        trainingTypeLabel1.setText("Tipo de Capacitación");

        topicLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(255, 255, 255));
        topicLabel.setText("Tema");

        imageLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageLabel.setText("Imagen");

        dateStartLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        dateStartLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateStartLabel.setText("Fecha Inicio");

        dateEndLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        dateEndLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateEndLabel.setText("Fecha Fin");

        maxQuantityLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        maxQuantityLabel.setForeground(new java.awt.Color(255, 255, 255));
        maxQuantityLabel.setText("Cantidad Max.");

        dayMaxLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        dayMaxLabel.setForeground(new java.awt.Color(255, 255, 255));
        dayMaxLabel.setText("Días Max.");

        totalHoursLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        totalHoursLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalHoursLabel.setText("Horas Totales");

        syllabusLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        syllabusLabel.setForeground(new java.awt.Color(255, 255, 255));
        syllabusLabel.setText("Temario");

        trainingTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        organizerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        modalityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        enviromentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        topicTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainDataPanelLayout = new javax.swing.GroupLayout(mainDataPanel);
        mainDataPanel.setLayout(mainDataPanelLayout);
        mainDataPanelLayout.setHorizontalGroup(
            mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainDataPanelLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(dateEndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(maxQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(totalHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainDataPanelLayout.createSequentialGroup()
                        .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(topicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(syllabusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateStartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainDataPanelLayout.createSequentialGroup()
                                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(organizerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(organizerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainDataPanelLayout.createSequentialGroup()
                                        .addComponent(modalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDataPanelLayout.createSequentialGroup()
                                        .addComponent(modalityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trainingTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trainingTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enviromentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enviromentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(topicTextField))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainDataPanelLayout.setVerticalGroup(
            mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDataPanelLayout.createSequentialGroup()
                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainDataPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(organizerLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(trainingTypeLabel1)
                        .addComponent(enviromentLabel)
                        .addComponent(modalityLabel)))
                .addGap(0, 0, 0)
                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modalityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainingTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviromentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(topicLabel)
                .addGap(0, 0, 0)
                .addComponent(topicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateStartLabel)
                .addGap(32, 32, 32)
                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageLabel)
                    .addComponent(dateEndLabel)
                    .addComponent(maxQuantityLabel)
                    .addComponent(dayMaxLabel)
                    .addComponent(totalHoursLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(syllabusLabel)
                .addGap(54, 54, 54))
        );

        tabPanel.addTab("Datos Principales", mainDataPanel);

        schedulePanel.setBackground(new java.awt.Color(23, 33, 42));

        javax.swing.GroupLayout schedulePanelLayout = new javax.swing.GroupLayout(schedulePanel);
        schedulePanel.setLayout(schedulePanelLayout);
        schedulePanelLayout.setHorizontalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        schedulePanelLayout.setVerticalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        tabPanel.addTab("Horario", schedulePanel);

        categoryPanel.setBackground(new java.awt.Color(23, 33, 42));

        javax.swing.GroupLayout categoryPanelLayout = new javax.swing.GroupLayout(categoryPanel);
        categoryPanel.setLayout(categoryPanelLayout);
        categoryPanelLayout.setHorizontalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        categoryPanelLayout.setVerticalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        tabPanel.addTab("Categorías", categoryPanel);

        organizerPanel.setBackground(new java.awt.Color(23, 33, 42));

        javax.swing.GroupLayout organizerPanelLayout = new javax.swing.GroupLayout(organizerPanel);
        organizerPanel.setLayout(organizerPanelLayout);
        organizerPanelLayout.setHorizontalGroup(
            organizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        organizerPanelLayout.setVerticalGroup(
            organizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        tabPanel.addTab("Organizadores", organizerPanel);

        settingPanel.setBackground(new java.awt.Color(23, 33, 42));

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        tabPanel.addTab("Configuración", settingPanel);

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topicTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JLabel dateEndLabel;
    private javax.swing.JLabel dateStartLabel;
    private javax.swing.JLabel dayMaxLabel;
    private javax.swing.JComboBox<String> enviromentCombo;
    private javax.swing.JLabel enviromentLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel mainDataPanel;
    private javax.swing.JLabel maxQuantityLabel;
    private javax.swing.JComboBox<String> modalityCombo;
    private javax.swing.JLabel modalityLabel;
    private javax.swing.JComboBox<String> organizerCombo;
    private javax.swing.JLabel organizerLabel;
    private javax.swing.JPanel organizerPanel;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JLabel syllabusLabel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JTextField topicTextField;
    private javax.swing.JLabel totalHoursLabel;
    private javax.swing.JComboBox<String> trainingTypeCombo;
    private javax.swing.JLabel trainingTypeLabel1;
    // End of variables declaration//GEN-END:variables
}
