package consejodepartamental.ui;

import consejodepartamental.entity.Capitulo;
import consejodepartamental.entity.EventoModalidad;
import consejodepartamental.entity.Organizador;
import consejodepartamental.entity.TipoEvento;
import consejodepartamental.logic.Controlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Diego
 */
public class SaveModularEventFrame extends javax.swing.JFrame {

    /**
     * Creates new form SaveModularEventFrame
     */
    private Controlador controlador;
    private List<Capitulo> capitulos;
    private List<EventoModalidad> modalidades;
    private List<TipoEvento> tipos;

    public SaveModularEventFrame() {
        initComponents();
        this.controlador = new Controlador();
        this.capitulos = new ArrayList<>();
        this.modalidades = new ArrayList<>();
        this.tipos = new ArrayList<>();

        this.capitulos.add(new Capitulo(0, "-"));
        this.capitulos.addAll(this.controlador.obtenerCapitulos());
        this.organizadorCombo.setModel(new DefaultComboBoxModel(this.capitulos.toArray()));

        this.modalidades.add(new EventoModalidad(0, "-"));
        this.modalidades.addAll(this.controlador.obtenerModalidades());
        this.modalidadCombo.setModel(new DefaultComboBoxModel(this.modalidades.toArray()));

        this.tipos.add(new TipoEvento(0, "-"));
        this.tipos.addAll(this.controlador.obtenerTipos());
        this.tipoCombo.setModel(new DefaultComboBoxModel(this.tipos.toArray()));

    }

    @Override
    public void dispose() {
        this.controlador.finalizar();
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        mainDataPanel = new javax.swing.JPanel();
        organizerLabel = new javax.swing.JLabel();
        modalityLabel = new javax.swing.JLabel();
        enviromentLabel = new javax.swing.JLabel();
        trainingTypeLabel1 = new javax.swing.JLabel();
        topicLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        dateStartLabel = new javax.swing.JLabel();
        dateEndLabel = new javax.swing.JLabel();
        maxQuantityLabel = new javax.swing.JLabel();
        dayMaxLabel = new javax.swing.JLabel();
        totalHoursLabel = new javax.swing.JLabel();
        syllabusLabel = new javax.swing.JLabel();
        tipoCombo = new javax.swing.JComboBox<>();
        organizadorCombo = new javax.swing.JComboBox<>();
        modalidadCombo = new javax.swing.JComboBox<>();
        ambienteCombo = new javax.swing.JComboBox<>();
        topicTextField = new javax.swing.JTextField();
        fechaInicioDate = new com.toedter.calendar.JDateChooser();
        fechaFinDate = new com.toedter.calendar.JDateChooser();
        cantidadSpinner = new javax.swing.JSpinner();
        diasSpinner = new javax.swing.JSpinner();
        horasSpiner = new javax.swing.JSpinner();
        imagenText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        temarioArea = new javax.swing.JTextArea();
        schedulePanel = new javax.swing.JPanel();
        categoryPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoriasTable = new javax.swing.JTable();
        categoriaBtnPanel = new javax.swing.JPanel();
        agregarCategoriaBtn = new javax.swing.JButton();
        removerCategoriaBtn = new javax.swing.JButton();
        organizerPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        organizadorBtnPanel = new javax.swing.JPanel();
        agregarOrganizadorBtn = new javax.swing.JButton();
        removerOrganizadorBtn = new javax.swing.JButton();
        settingPanel = new javax.swing.JPanel();
        eventoMonitoreadoCheck = new javax.swing.JCheckBox();
        correoMatriculaCheck = new javax.swing.JCheckBox();
        correoDocenteCheck = new javax.swing.JCheckBox();
        guardarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(23, 33, 42));

        tabPanel.setBackground(new java.awt.Color(23, 33, 42));
        tabPanel.setForeground(new java.awt.Color(255, 255, 255));
        tabPanel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N

        mainDataPanel.setBackground(new java.awt.Color(23, 33, 42));
        mainDataPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainDataPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainDataPanel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N

        organizerLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        organizerLabel.setForeground(new java.awt.Color(255, 255, 255));
        organizerLabel.setText("Organizadores");

        modalityLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        modalityLabel.setForeground(new java.awt.Color(255, 255, 255));
        modalityLabel.setText("Modalidad");

        enviromentLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        enviromentLabel.setForeground(new java.awt.Color(255, 255, 255));
        enviromentLabel.setText("Ambiente");

        trainingTypeLabel1.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        trainingTypeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        trainingTypeLabel1.setText("Tipo de Capacitación");

        topicLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(255, 255, 255));
        topicLabel.setText("Tema");

        imageLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageLabel.setText("Imagen");

        dateStartLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        dateStartLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateStartLabel.setText("Fecha Inicio");

        dateEndLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        dateEndLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateEndLabel.setText("Fecha Fin");

        maxQuantityLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        maxQuantityLabel.setForeground(new java.awt.Color(255, 255, 255));
        maxQuantityLabel.setText("Cantidad Max.");

        dayMaxLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        dayMaxLabel.setForeground(new java.awt.Color(255, 255, 255));
        dayMaxLabel.setText("Días Max.");

        totalHoursLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        totalHoursLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalHoursLabel.setText("Horas Totales");

        syllabusLabel.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        syllabusLabel.setForeground(new java.awt.Color(255, 255, 255));
        syllabusLabel.setText("Temario");

        tipoCombo.setEditable(true);

        organizadorCombo.setEditable(true);

        modalidadCombo.setEditable(true);

        ambienteCombo.setEditable(true);

        topicTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicTextFieldActionPerformed(evt);
            }
        });

        fechaInicioDate.setDateFormatString("yyyy-MM-dd");

        fechaFinDate.setDateFormatString("yyyy-MM-dd");

        temarioArea.setColumns(20);
        temarioArea.setRows(5);
        jScrollPane1.setViewportView(temarioArea);

        javax.swing.GroupLayout mainDataPanelLayout = new javax.swing.GroupLayout(mainDataPanel);
        mainDataPanel.setLayout(mainDataPanelLayout);
        mainDataPanelLayout.setHorizontalGroup(
            mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(topicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(syllabusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainDataPanelLayout.createSequentialGroup()
                            .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(organizerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(organizadorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainDataPanelLayout.createSequentialGroup()
                                    .addComponent(modalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(83, 83, 83))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDataPanelLayout.createSequentialGroup()
                                    .addComponent(modalidadCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(trainingTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enviromentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ambienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(topicTextField)
                        .addGroup(mainDataPanelLayout.createSequentialGroup()
                            .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainDataPanelLayout.createSequentialGroup()
                                    .addComponent(dateStartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dateEndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainDataPanelLayout.createSequentialGroup()
                                    .addComponent(fechaInicioDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(fechaFinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainDataPanelLayout.createSequentialGroup()
                                    .addComponent(maxQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dayMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainDataPanelLayout.createSequentialGroup()
                                    .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(diasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(totalHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(horasSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(imagenText, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        mainDataPanelLayout.setVerticalGroup(
            mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDataPanelLayout.createSequentialGroup()
                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainDataPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(organizerLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(trainingTypeLabel1)
                        .addComponent(enviromentLabel)
                        .addComponent(modalityLabel)))
                .addGap(0, 0, 0)
                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizadorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modalidadCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(topicLabel)
                .addGap(0, 0, 0)
                .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainDataPanelLayout.createSequentialGroup()
                        .addComponent(topicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateStartLabel)
                            .addComponent(dateEndLabel)
                            .addComponent(maxQuantityLabel)
                            .addComponent(dayMaxLabel)
                            .addComponent(totalHoursLabel)
                            .addComponent(imageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaInicioDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(diasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(horasSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(imagenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(fechaFinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(syllabusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        tabPanel.addTab("Datos Principales", mainDataPanel);

        schedulePanel.setBackground(new java.awt.Color(23, 33, 42));
        schedulePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout schedulePanelLayout = new javax.swing.GroupLayout(schedulePanel);
        schedulePanel.setLayout(schedulePanelLayout);
        schedulePanelLayout.setHorizontalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        schedulePanelLayout.setVerticalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        tabPanel.addTab("Horario", schedulePanel);

        categoryPanel.setBackground(new java.awt.Color(23, 33, 42));
        categoryPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        categoriasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Matrícula", "Certificado", "Cuotas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(categoriasTable);
        if (categoriasTable.getColumnModel().getColumnCount() > 0) {
            categoriasTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            categoriasTable.getColumnModel().getColumn(1).setPreferredWidth(8);
            categoriasTable.getColumnModel().getColumn(2).setPreferredWidth(8);
            categoriasTable.getColumnModel().getColumn(3).setPreferredWidth(8);
        }

        categoriaBtnPanel.setBackground(new java.awt.Color(23, 33, 42));
        categoriaBtnPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        agregarCategoriaBtn.setBackground(new java.awt.Color(23, 33, 42));
        agregarCategoriaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/add.png"))); // NOI18N

        removerCategoriaBtn.setBackground(new java.awt.Color(23, 33, 42));
        removerCategoriaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/remove.png"))); // NOI18N

        javax.swing.GroupLayout categoriaBtnPanelLayout = new javax.swing.GroupLayout(categoriaBtnPanel);
        categoriaBtnPanel.setLayout(categoriaBtnPanelLayout);
        categoriaBtnPanelLayout.setHorizontalGroup(
            categoriaBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriaBtnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(categoriaBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removerCategoriaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarCategoriaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        categoriaBtnPanelLayout.setVerticalGroup(
            categoriaBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriaBtnPanelLayout.createSequentialGroup()
                .addComponent(agregarCategoriaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerCategoriaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout categoryPanelLayout = new javax.swing.GroupLayout(categoryPanel);
        categoryPanel.setLayout(categoryPanelLayout);
        categoryPanelLayout.setHorizontalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(categoriaBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        categoryPanelLayout.setVerticalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tabPanel.addTab("Categorías", categoryPanel);

        organizerPanel.setBackground(new java.awt.Color(23, 33, 42));
        organizerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CIP", "DNI", "Organizador", "Celular", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(8);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(8);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(8);
        }

        organizadorBtnPanel.setBackground(new java.awt.Color(23, 33, 42));
        organizadorBtnPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        agregarOrganizadorBtn.setBackground(new java.awt.Color(23, 33, 42));
        agregarOrganizadorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/add.png"))); // NOI18N

        removerOrganizadorBtn.setBackground(new java.awt.Color(23, 33, 42));
        removerOrganizadorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/remove.png"))); // NOI18N

        javax.swing.GroupLayout organizadorBtnPanelLayout = new javax.swing.GroupLayout(organizadorBtnPanel);
        organizadorBtnPanel.setLayout(organizadorBtnPanelLayout);
        organizadorBtnPanelLayout.setHorizontalGroup(
            organizadorBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizadorBtnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(organizadorBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removerOrganizadorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarOrganizadorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        organizadorBtnPanelLayout.setVerticalGroup(
            organizadorBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizadorBtnPanelLayout.createSequentialGroup()
                .addComponent(agregarOrganizadorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerOrganizadorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout organizerPanelLayout = new javax.swing.GroupLayout(organizerPanel);
        organizerPanel.setLayout(organizerPanelLayout);
        organizerPanelLayout.setHorizontalGroup(
            organizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organizadorBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        organizerPanelLayout.setVerticalGroup(
            organizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(organizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizadorBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        tabPanel.addTab("Organizadores", organizerPanel);

        settingPanel.setBackground(new java.awt.Color(23, 33, 42));
        settingPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eventoMonitoreadoCheck.setBackground(new java.awt.Color(23, 33, 42));
        eventoMonitoreadoCheck.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        eventoMonitoreadoCheck.setForeground(new java.awt.Color(255, 255, 255));
        eventoMonitoreadoCheck.setText("Evento Monitoreado externamente");
        eventoMonitoreadoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMonitoreadoCheckActionPerformed(evt);
            }
        });

        correoMatriculaCheck.setBackground(new java.awt.Color(23, 33, 42));
        correoMatriculaCheck.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        correoMatriculaCheck.setForeground(new java.awt.Color(255, 255, 255));
        correoMatriculaCheck.setText("Enviar correo por matrícula");

        correoDocenteCheck.setBackground(new java.awt.Color(23, 33, 42));
        correoDocenteCheck.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        correoDocenteCheck.setForeground(new java.awt.Color(255, 255, 255));
        correoDocenteCheck.setText("Enviar correo al docente");

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eventoMonitoreadoCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoMatriculaCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addComponent(correoDocenteCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(eventoMonitoreadoCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correoMatriculaCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correoDocenteCheck)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        tabPanel.addTab("Configuración", settingPanel);

        guardarBtn.setText("Guardar");

        cancelarBtn.setText("Cancelar");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelarBtn)
                .addGap(35, 35, 35))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topicTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicTextFieldActionPerformed

    private void eventoMonitoreadoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMonitoreadoCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventoMonitoreadoCheckActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCategoriaBtn;
    private javax.swing.JButton agregarCategoriaBtn1;
    private javax.swing.JButton agregarCategoriaBtn2;
    private javax.swing.JButton agregarCategoriaBtn3;
    private javax.swing.JButton agregarOrganizadorBtn;
    private javax.swing.JComboBox<String> ambienteCombo;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JPanel categoriaBtnPanel;
    private javax.swing.JTable categoriasTable;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JCheckBox correoDocenteCheck;
    private javax.swing.JCheckBox correoMatriculaCheck;
    private javax.swing.JLabel dateEndLabel;
    private javax.swing.JLabel dateStartLabel;
    private javax.swing.JLabel dayMaxLabel;
    private javax.swing.JSpinner diasSpinner;
    private javax.swing.JLabel enviromentLabel;
    private javax.swing.JCheckBox eventoMonitoreadoCheck;
    private com.toedter.calendar.JDateChooser fechaFinDate;
    private com.toedter.calendar.JDateChooser fechaInicioDate;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JSpinner horasSpiner;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imagenText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainDataPanel;
    private javax.swing.JLabel maxQuantityLabel;
    private javax.swing.JComboBox<String> modalidadCombo;
    private javax.swing.JLabel modalityLabel;
    private javax.swing.JPanel organizadorBtnPanel;
    private javax.swing.JComboBox<String> organizadorCombo;
    private javax.swing.JLabel organizerLabel;
    private javax.swing.JPanel organizerPanel;
    private javax.swing.JButton removerCategoriaBtn;
    private javax.swing.JButton removerCategoriaBtn1;
    private javax.swing.JButton removerCategoriaBtn2;
    private javax.swing.JButton removerCategoriaBtn3;
    private javax.swing.JButton removerOrganizadorBtn;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JLabel syllabusLabel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextArea temarioArea;
    private javax.swing.JComboBox<String> tipoCombo;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JTextField topicTextField;
    private javax.swing.JLabel totalHoursLabel;
    private javax.swing.JLabel trainingTypeLabel1;
    // End of variables declaration//GEN-END:variables
}
